name: Publish package to GitHub Packages

on:
  workflow_run:
    workflows: ["Release Version"]
    types: [completed]
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: 'Checkout to master branch'
        uses: actions/checkout@master
        with:
          ref: master

      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@fleye-me'

      - run: npm ci

      - name: Build project
        run: npm run build

      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
